version: "3"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  gofmt:
    cmds:
      - command -v goimports || go install golang.org/x/tools/cmd/goimports@latest
      - gofmt -s -w .
      - goimports -w .

  govulncheck:
    desc: vulnerability detection
    cmds:
      - command -v govulncheck || go install golang.org/x/vuln/cmd/govulncheck@latest
      - govulncheck ./...

  golint:
    desc: lint code
    cmds:
      - command -v golangci-lint || go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.8.0
      - golangci-lint run -v ./...

  gci:
    cmds:
      - command -v gci || go install github.com/daixiang0/gci
      - gci write --skip-generated --custom-order -s standard -s "prefix(github.com/ysicing/caddy2-ipban)" -s default -s blank -s dot .

  fmt:
    desc: Run all formatters (gofmt + goimports + gci)
    cmds:
      - task: gofmt
      - task: gci

  build:
    desc: Build caddy with ipban plugin via xcaddy
    cmds:
      - xcaddy build --with github.com/ysicing/caddy2-ipban=.

  test:
    desc: Run all tests
    cmds:
      - go test -count=1 ./...

  test:race:
    desc: Run tests with race detector
    cmds:
      - go test -race -count=1 ./...

  test:verbose:
    desc: Run tests with verbose output
    cmds:
      - go test -v -count=1 ./...

  vet:
    desc: Run static analysis
    cmds:
      - go vet ./...

  lint:
    desc: Run all checks (vet + test + race)
    cmds:
      - task: vet
      - task: test:race

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f caddy
      - go clean -cache -testcache

  test:e2e:
    desc: Build and run E2E test against local caddy
    deps: [build]
    cmds:
      - ./testdata/test.sh
